urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'mecanografia.requisicao_copias.views.index', name='index'),
    url(r'^material/', 'mecanografia.requisicao_copias.views.material', name='material'),
    url(r'^cadastrar_material/', 'mecanografia.requisicao_copias.views.cadastrar_material', name='cadastrar_material'),
    url(r'^editar_material/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.editar_material', name='editar_material'),
    url(r'^excluir_material/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.excluir_material', name='excluir_material'),    
    url(r'^setor/', 'mecanografia.requisicao_copias.views.setor', name='setor'),
    url(r'^cadastrar_setor/', 'mecanografia.requisicao_copias.views.cadastrar_setor', name='cadastrar_setor'),
    url(r'^editar_setor/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.editar_setor', name='editar_setor'),
    url(r'^excluir_setor/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.excluir_setor', name='excluir_setor'),
    
    
    url(r'^vincular_setor/', 'mecanografia.requisicao_copias.views.vincular_setor', name='vincular_setor'),
    
        
    url(r'^servidor/', 'mecanografia.requisicao_copias.views.servidor', name='servidor'),
    url(r'^cadastrar_servidor/', 'mecanografia.requisicao_copias.views.cadastrar_servidor', name='cadastrar_servidor'),
    url(r'^editar_servidor/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.editar_servidor', name='editar_servidor'),
    url(r'^excluir_servidor/(?P<codigo>\d+)', 'mecanografia.requisicao_copias.views.excluir_servidor', name='excluir_servidor'),    
    url(r'^media/(.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT}),
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'logout.html', 'next_page': '/login'}),
)

aplicacao/models.py
#coding: utf-8

from django.db import models
from django.forms import ModelForm, ChoiceField, RadioSelect
from django import forms
from django.db import connection, transaction
from ddiex_social.aplicacao.validacao import UploadFile


#modelos
class Bolsa(models.Model):
    modalidade = models.CharField("Modalidade", max_length=50)
    valor_auxilio = models.CharField("Valor do Auxílio", max_length=50)
    carga_horaria = models.CharField("Carga Horária", max_length=50)
    
    def __unicode__(self):
        return self.modalidade
        
    
class Edital(models.Model):
    numero_edital = models.CharField("Número", max_length=50)
    descricao = models.CharField("Descrição", max_length=50)
    bolsa = models.ForeignKey('Bolsa')
    data_publicacao = models.CharField("Data da Publicação", max_length=50)
    data_expiracao = models.CharField("Data de Expiração", max_length=50)
    inicio_inscricao = models.CharField("Início da Inscrição", max_length=50)
    fim_inscricao = models.CharField("Início da Inscrição", max_length=50)
    hora_inicio = models.CharField("Hora de Início da Inscrição", max_length=50)
    hora_fim = models.CharField("Hora de Término da Inscrição", max_length=50)
    arquivo = UploadFile(upload_to='site/editais', max_upload_size=10000000, blank=False)
    
    def __unicode__(self):
        return self.numero_edital
        
        
class Setor(models.Model):
    descricao = models.CharField("Descricao", max_length=50)
    
    def __unicode__(self):
        return self.descricao
        
    


class Inscricao(models.Model):
    matricula = models.CharField("matricula", max_length=50)
    edital = models.CharField("Edital", max_length=50)
    nome = models.CharField("Nome", max_length=50)
    documento_identificacao = models.CharField("RG", max_length=50)
    cpf = models.CharField("CPF", max_length=50)
    email = models.CharField("E-mail", max_length=50)
    telefone = models.CharField("Telefone", max_length=50)
    celular = models.CharField("Celular", max_length=50)
    
    def __unicode__(self):
        return self.id       


class Bolsista(models.Model):
    matricula = models.CharField("matricula", max_length=50)
    nome = models.CharField("Nome", max_length=50)
    documento_identificacao = models.CharField("Documento de Identificação", max_length=50)
    cpf = models.CharField("CPF", max_length=50)
    inicio_bolsa = models.CharField("Data de Início da Bolsa", max_length=50)
    termino_bolsa = models.CharField("Data de Término da Bolsa", max_length=50)
    setor = models.ForeignKey('Setor')
    Bolsa = models.ForeignKey('Bolsa')
    banco = models.CharField("Banco", max_length=50)
    agencia = models.CharField("Agencia", max_length=50)
    conta_corrente = models.CharField("Conta Corrente", max_length=50)
    email = models.CharField("E-mail", max_length=50)
    telefone = models.CharField("Telefone", max_length=50)
    celular = models.CharField("Celular", max_length=50)
    
    def __unicode__(self):
        return self.nome
        
        
class AjudaCusto(models.Model):
    matricula = models.CharField("matricula", max_length=50)
    nome = models.CharField("Nome", max_length=50)
    documento_identificacao = models.CharField("RG", max_length=50)
    cpf = models.CharField("CPF", max_length=50)
    valor = models.CharField("Valor", max_length=50)
    justificativa = models.CharField("Justificativa", max_length=50)
    
    def __unicode__(self):
        return self.id               
        
        
            

#Formularios
class BolsaForm(ModelForm):
    class Meta:
        model = Bolsa
        
        
        
class EditalForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditalForm, self).__init__(*args, **kwargs)

        bolsa = ['bolsa']
        for b in bolsa:
            self.fields[b].widget = forms.Select(choices = self.consulta())
             
    def consulta(self):
        bolsa = Bolsa.objects.all()
        self.bolsa = [(0,'')]
        for b in bolsa:
            self.bolsa.append((b.id, b.modalidade))
        return self.bolsa
        
    class Meta:
        model = Edital
        

class SetorForm(ModelForm):
    class Meta:
        model = Setor

        

        
        
class InscricaoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(InscricaoForm, self).__init__(*args, **kwargs)

        
            
        edital = ['edital']
        for e in edital:
            self.fields[e].widget = forms.HiddenInput(attrs={'value':'{{codigo}}'})    
            
    def consulta(self, numero_edital):
        setor = SetorEdital.objects.filter(edital=numero_edital)
        for s in setor:
            self.setor.append((s.setor_id, s.descricao))
        return self.setor
            
    class Meta:
        model = Inscricao
        
        
class BolsistaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BolsistaForm, self).__init__(*args, **kwargs)
        
        bolsa = ['Bolsa']
        for b in bolsa:
            self.fields[b].widget = forms.Select(choices = self.consulta())
             
    def consulta(self):
        bolsa = Bolsa.objects.all()
        self.bolsa = [(0,'')]
        for b in bolsa:
            self.bolsa.append((b.id, b.modalidade))
        return self.bolsa
            
    class Meta:
        model = Bolsista
        
        
class AjudaCustoForm(ModelForm):
               
    class Meta:
        model = AjudaCusto

aplicacao/views.py
# coding: utf-8 

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from ddiex_social.aplicacao.models import Bolsa, BolsaForm, Edital, EditalForm, Setor, SetorForm, Inscricao, InscricaoForm, Bolsista, BolsistaForm, AjudaCusto, AjudaCustoForm
from django.core.urlresolvers import reverse
from django.core.mail import send_mail, get_connection, EmailMessage
#from reportlab.pdfgen import canvas
#from reportlab.lib.units import inch
import os
from django.core.urlresolvers import reverse
from cStringIO import StringIO
#from reportlab.lib import colors
#from reportlab.lib.pagesizes import letter, A4
#from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
#from reportlab.lib.styles import getSampleStyleSheet
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction
from django.core.files.storage import default_storage
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
import mimetypes, os



#pagina principal
def index(request):
    edital = Edital.objects.all()
    return render_to_response('index.html', {'edital':edital, 'user':request.user})
   

#cadastro de bolsa
@login_required
def cadastrar_bolsa(request):
    if request.POST:
        f = BolsaForm(request.POST)
        if f.is_valid():
            f.save()
            mensagem = 'Bolsa cadastrada com sucesso.'
            formulario = 'Cadastro de Bolsa'
            voltar = '/bolsa/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response('cadastrar_bolsa.html', {'user':request.user, 'form':f, 'erro': erro})
    else:
        f = BolsaForm()
        return render_to_response('cadastrar_bolsa.html', {'user':request.user, 'form':f})

#consulta e acesso aos dados de bolsa
@login_required
def bolsa(request):
    consulta = Bolsa.objects.all().order_by('modalidade')
    return render_to_response('bolsa.html', {'user':request.user, 'consulta': consulta})

#alteração de dados de materiais
@login_required
def editar_bolsa(request, codigo):
    bolsa = get_object_or_404(Bolsa, pk = codigo)
    f = BolsaForm(request.POST, instance = bolsa)
    if request.POST:
        if f.is_valid():
            bolsa = f.save()
            mensagem = 'Bolsa alterada com sucesso.'
            formulario = 'Editar Bolsa'
            voltar = '/bolsa/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response("editar_bolsa.html", {'user':request.user, 'form':f, 'erro': erro})
    else:
        codigo = bolsa.id
        f = BolsaForm(instance=bolsa)
        return render_to_response('editar_bolsa.html', {'form':f, 'codigo':codigo, 'user':request.user})

#excluir bolsa
@login_required
def excluir_bolsa(request, codigo):
    bolsa = get_object_or_404(Bolsa, pk=codigo)
    bolsa.delete()
    mensagem = 'Bolsa excluída com sucesso.'
    formulario = 'Excluir Bolsa'
    voltar = '/bolsa/'
    return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})




#cadastro de bolsa
@login_required
def cadastrar_setor(request):
    if request.POST:
        f = SetorForm(request.POST)
        if f.is_valid():
            f.save()
            mensagem = 'Setor cadastrado com sucesso.'
            formulario = 'Cadastro de setor'
            voltar = '/setor/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response('cadastrar_setor.html', {'user':request.user, 'form':f, 'erro': erro})
    else:
        f = SetorForm()
        return render_to_response('cadastrar_setor.html', {'user':request.user, 'form':f})

#consulta e acesso aos dados de bolsa
@login_required
def setor(request):
    consulta = Setor.objects.all().order_by('descricao')
    return render_to_response('setor.html', {'user':request.user, 'consulta': consulta})

#alteração de dados de materiais
@login_required
def editar_setor(request, codigo):
    setor = get_object_or_404(Setor, pk = codigo)
    f = SetorForm(request.POST, instance = setor)
    if request.POST:
        if f.is_valid():
            setor = f.save()
            mensagem = 'Setor alterado com sucesso.'
            formulario = 'Editar Setor'
            voltar = '/setor/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response("editar_setor.html", {'user':request.user, 'form':f, 'erro': erro})
    else:
        codigo = setor.id
        f = SetorForm(instance=setor)
        return render_to_response('editar_setor.html', {'form':f, 'codigo':codigo, 'user':request.user})

#excluir bolsa
@login_required
def excluir_setor(request, codigo):
    setor = get_object_or_404(Setor, pk=codigo)
    setor.delete()
    mensagem = 'Setor excluído com sucesso.'
    formulario = 'Excluir Setor'
    voltar = '/setor/'
    return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})    
    




#cadastro de bolsa
@login_required
def cadastrar_ajuda_custo(request):
    if request.POST:
        f = AjudaCustoForm(request.POST)
        if f.is_valid():
            f.save()
            mensagem = 'Ajuda de Custo cadastrado com sucesso.'
            formulario = 'Cadastro de Ajuda de Custo'
            voltar = '/ajuda_custo/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response('cadastrar_ajuda_custo.html', {'user':request.user, 'form':f, 'erro': erro})
    else:
        f = AjudaCustoForm()
        return render_to_response('cadastrar_ajuda_custo.html', {'user':request.user, 'form':f})

#consulta e acesso aos dados de bolsa
@login_required
def ajuda_custo(request):
    consulta = AjudaCusto.objects.all().order_by('nome')
    return render_to_response('ajuda_custo.html', {'user':request.user, 'consulta': consulta})

#alteração de dados de materiais
@login_required
def editar_ajuda_custo(request, codigo):
    ajuda_custo = get_object_or_404(AjudaCusto, pk = codigo)
    f = AjudaCustoForm(request.POST, instance = ajuda_custo)
    if request.POST:
        if f.is_valid():
            ajuda_custo = f.save()
            mensagem = 'Ajuda de Custo alterada com sucesso.'
            formulario = 'Editar Ajuda de Custo'
            voltar = '/ajuda_custo/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response("editar_ajuda_custo.html", {'user':request.user, 'form':f, 'erro': erro})
    else:
        codigo = ajuda_custo.id
        f = AjudaCustoForm(instance=ajuda_custo)
        return render_to_response('editar_ajuda_custo.html', {'form':f, 'codigo':codigo, 'user':request.user})

#excluir bolsa
@login_required
def excluir_ajuda_custo(request, codigo):
    ajuda_custo = get_object_or_404(AjudaCusto, pk=codigo)
    ajuda_custo.delete()
    mensagem = 'Ajuda de custo excluída com sucesso.'
    formulario = 'Excluir Ajuda de custo'
    voltar = '/ajuda_custo/'
    return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})    
    
    
    
    
    
    
#cadastro de bolsa
@login_required
def cadastrar_bolsista(request):
    if request.POST:
        f = BolsistaForm(request.POST)
        if f.is_valid():
            f.save()
            mensagem = 'Bolsista cadastrado com sucesso.'
            formulario = 'Cadastro de Bolsista'
            voltar = '/bolsista/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response('bolsista.html', {'user':request.user, 'form':f, 'erro': erro})
    else:
        f = BolsistaForm()
        return render_to_response('cadastrar_bolsista.html', {'user':request.user, 'form':f})

#consulta e acesso aos dados de bolsa
@login_required
def bolsista(request):
    consulta = Bolsista.objects.all().order_by('nome')
    return render_to_response('bolsista.html', {'user':request.user, 'consulta': consulta})

#alteração de dados de materiais
@login_required
def editar_bolsista(request, codigo):
    bolsista = get_object_or_404(Bolsista, pk = codigo)
    f = BolsistaForm(request.POST, instance = bolsista)
    if request.POST:
        if f.is_valid():
            bolsista = f.save()
            mensagem = 'Bolsista alterado com sucesso.'
            formulario = 'Editar bolsista'
            voltar = '/bolsista/'
            return render_to_response('sucesso.html', {'user':request.user, 'mensagem':mensagem, 'link':voltar, 'formulario':formulario})
        else:
            erro = True
            return render_to_response("editar_bolsista.html", {'user':request.user, 'form':f, 'erro': erro})
    else:
        codigo = bolsista.id
        f = BolsistaForm(instance=bolsista)
        return render_to_response('editar_bolsista.html', {'form':f, 'codigo':codigo, 'user':request.user})

#excluir bolsa
@login_required
def excluir_bolsista(request, codigo):
    bolsista = get_object_or_404(Bolsista, pk=codigo)
    bolsista.delete()

aplicacao/templates/cadastrar_bolsista.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone").mask("(99) 9999-9999");
            $("#id_celular").mask("(99) 9999-9999");
            $("#id_data_emissao").mask("99/99/9999");
            $("#id_cep").mask("99.999-999");
            $("#id_pis").mask("999.99999.99-9");
        });
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome.value=elemento.nome.value.toUpperCase();
            elemento.orgao_expedidor.value=elemento.orgao_expedidor.value.toUpperCase();
            elemento.logradouro.value=elemento.logradouro.value.toUpperCase();
            elemento.complemento.value=elemento.complemento.value.toUpperCase();
            elemento.bairro.value=elemento.bairro.value.toUpperCase();
            elemento.cidade.value=elemento.cidade.value.toUpperCase();
            elemento.uf.value=elemento.uf.value.toUpperCase();            
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }        
    </script> 
{% endblock scripts %}
{% block subtitle %}
    <center> Cadastro de Bolsista </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="" enctype="multipart/form-data" method="post">
        <table align="center">
            <fildset> 
                {{form.as_table}}                           
                <tr><td>&nbsp;</td></tr>                            
                 
	            <tr>
                    <td colspan="2">
                        <input type="submit" value="Cadastrar"/>
                        <input type="button" value="Voltar" onclick="history.go(-1)">
                    </td>
	            </tr>
	    </table>
    </form>   
{% endblock conteudo %}

aplicacao/templates/cadastrar_edital.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone").mask("(99) 9999-9999");
            $("#id_celular").mask("(99) 9999-9999");
            $("#id_data_emissao").mask("99/99/9999");
            $("#id_cep").mask("99.999-999");
            $("#id_pis").mask("999.99999.99-9");
        });
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome.value=elemento.nome.value.toUpperCase();
            elemento.orgao_expedidor.value=elemento.orgao_expedidor.value.toUpperCase();
            elemento.logradouro.value=elemento.logradouro.value.toUpperCase();
            elemento.complemento.value=elemento.complemento.value.toUpperCase();
            elemento.bairro.value=elemento.bairro.value.toUpperCase();
            elemento.cidade.value=elemento.cidade.value.toUpperCase();
            elemento.uf.value=elemento.uf.value.toUpperCase();            
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }        
    </script> 
{% endblock scripts %}
{% block subtitle %}
    <center> Cadastro de Edital </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="" enctype="multipart/form-data" method="post">
        <table align="center">
            <fildset> 
                {{form.as_table}}                           
                <tr><td>&nbsp;</td></tr>                            
                 
	            <tr>
                    <td colspan="2">
                        <input type="submit" value="Cadastrar"/>
                        <input type="button" value="Voltar" onclick="history.go(-1)">
                    </td>
	            </tr>
	    </table>
    </form>   
{% endblock conteudo %}

aplicacao/templates/editar_ajuda_custo.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone").mask("(99) 9999-9999");
            $("#id_celular").mask("(99) 9999-9999");
            $("#id_data_emissao").mask("99/99/9999");
            $("#id_cep").mask("99.999-999");
            $("#id_pis").mask("999.99999.99-9");
        });
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome.value=elemento.nome.value.toUpperCase();
            elemento.orgao_expedidor.value=elemento.orgao_expedidor.value.toUpperCase();
            elemento.logradouro.value=elemento.logradouro.value.toUpperCase();
            elemento.complemento.value=elemento.complemento.value.toUpperCase();
            elemento.bairro.value=elemento.bairro.value.toUpperCase();
            elemento.cidade.value=elemento.cidade.value.toUpperCase();
            elemento.uf.value=elemento.uf.value.toUpperCase();            
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }        
    </script>
{% endblock scripts %}
{% block subtitle %}
    <center> Editar Ajuda de Custo </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="/editar_ajuda_custo/{{codigo}}" enctype="multipart/form-data" method="post">
        <table align="center">
            <fildset>      
                {{form.as_table}}                      
                <tr><td>&nbsp;</td></tr>                            
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Alterar"/>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" value="Excluir" onclick="location.href='/excluir_ajuda_custo/{{codigo}}/'">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" value="Voltar" onclick="history.go(-1)">
                    </td>
	            </tr>
	    </table>
    </form>   
{% endblock conteudo %}

aplicacao/templates/editar_edital.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone").mask("(99) 9999-9999");
            $("#id_celular").mask("(99) 9999-9999");
            $("#id_data_emissao").mask("99/99/9999");
            $("#id_cep").mask("99.999-999");
            $("#id_pis").mask("999.99999.99-9");
        });
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome.value=elemento.nome.value.toUpperCase();
            elemento.orgao_expedidor.value=elemento.orgao_expedidor.value.toUpperCase();
            elemento.logradouro.value=elemento.logradouro.value.toUpperCase();
            elemento.complemento.value=elemento.complemento.value.toUpperCase();
            elemento.bairro.value=elemento.bairro.value.toUpperCase();
            elemento.cidade.value=elemento.cidade.value.toUpperCase();
            elemento.uf.value=elemento.uf.value.toUpperCase();            
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }        
    </script>
{% endblock scripts %}
{% block subtitle %}
    <center> Editar Edital </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="/editar_edital/{{codigo}}" enctype="multipart/form-data" method="post">
        <table align="center">
            <fildset>      
                {{form.as_table}}                      
                <tr><td>&nbsp;</td></tr>                            
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Alterar"/>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" value="Excluir" onclick="location.href='/excluir_edital/{{codigo}}/'">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" value="Voltar" onclick="history.go(-1)">
                    </td>
	            </tr>
	    </table>
    </form>   
{% endblock conteudo %}

aplicacao/templates/inscricao.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript">
        $.noConflict( )
        function maiuscula(valor){
            var elemento=document.form;
            elemento.descricao.value=elemento.descricao.value.toUpperCase();
        }        
    </script> 
{% endblock scripts %}
{% block subtitle %}
    <center> Inscrição </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="" enctype="multipart/form-data" method="post">
        <table align="center">
            <fildset>                            
                
	            <tbody><tr><th><label for="id_matricula">Matricula:</label></th><td><input type="text" maxlength="50" name="matricula" id="id_matricula"></td></tr>
<tr><th><label for="id_nome">Nome:</label></th><td><input type="text" maxlength="50" name="nome" id="id_nome"></td></tr>
<tr><th><label for="id_documento_identificacao">RG:</label></th><td><input type="text" maxlength="50" name="documento_identificacao" id="id_documento_identificacao"></td></tr>
<tr><th><label for="id_cpf">CPF:</label></th><td><input type="text" maxlength="50" name="cpf" id="id_cpf"></td></tr>
<tr><th><label for="id_email">E-mail:</label></th><td><input type="text" maxlength="50" name="email" id="id_email"></td></tr>
<tr><th><label for="id_telefone">Telefone:</label></th><td><input type="text" maxlength="50" name="telefone" id="id_telefone"></td></tr>
<tr><th><label for="id_celular">Celular:</label></th><td><input type="text" maxlength="50" name="celular" id="id_celular"><input type="hidden" id="id_edital" value="{{codigo}}" name="edital"></td></tr>
	            <tr>
                    <td colspan="2">
                        <input type="submit" value="Inscrever">
                        <input type="button" onclick="history.go(-1)" value="Voltar">
                    </td>
	            </tr>
	    </tbody>
	    </table>
    </form>   
{% endblock conteudo %}